#Dictionary of sanskrit/hindi words
dictionary = {
    'ॐ' : 'oṁ',
    'ऀ' : 'ṁ',
    'ँ' : 'ṃ',
    'ं' : 'ṃ',
    'ः' : 'ḥ',
    'अ' : 'a',
    'आ' : 'ā',
    'इ' : 'i',
    'ई' : 'ī',
    'उ' : 'u',
    'ऊ' : 'ū',
    'ऋ' : 'r̥',
    'ॠ' : ' r̥̄',
    'ऌ' : 'l̥',
    'ॡ' : ' l̥̄',
    'ऍ' : 'ê',
    'ऎ' : 'e',
    'ए' : 'e',
    'ऐ' : 'ai',
    'ऑ' : 'ô',
    'ऒ' : 'o',
    'ओ' : 'o',
    'औ' : 'au',
    'ा' : 'ā',
    'ि' : 'i',
    'ी' : 'ī',
    'ु' : 'u',
    'ू' : 'ū',
    'ृ' : 'r̥',
    'ॄ' : ' r̥̄',
    'ॢ' : 'l̥',
    'ॣ' : ' l̥̄',
    'ॅ' : 'ê',
    'े' : 'e',
    'ै' : 'ai',
    'ॉ' : 'ô',
    'ो' : 'o',
    'ौ' : 'au',
    'क़' : 'q',
    'क' : 'k',
    'ख़' : 'x',
    'ख' : 'kh',
    'ग़' : 'ġ',
    'ग' : 'g',
    'ॻ' : 'g',
    'घ' : 'gh',
    'ङ' : 'ṅ',
    'च' : 'c',
    'छ' : 'ch',
    'ज़' : 'z',
    'ज' : 'j',
    'ॼ' : 'j',
    'झ' : 'jh',
    'ञ' : 'ñ',
    'ट' : 'ṭ',
    'ठ' : 'ṭh',
    'ड़' : 'ṛ',
    'ड' : 'ḍ',
    'ॸ' : 'ḍ',
    'ॾ' : 'd',
    'ढ़' : 'ṛh',
    'ढ' : 'ḍh',
    'ण' : 'ṇ',
    'त' : 't',
    'थ' : 'th',
    'द' : 'd',
    'ध' : 'dh',
    'न' : 'n',
    'प' : 'p',
    'फ़' : 'f',
    'फ' : 'ph',
    'ब' : 'b',
    'ॿ' : 'b',
    'भ' : 'bh',
    'म' : 'm',
    'य' : 'y',
    'र' : 'r',
    'ल' : 'l',
    'ळ' : 'ḷ',
    'व' : 'v',
    'श' : 'ś',
    'ष' : 'ṣ',
    'स' : 's',
    'ह' : 'h',
    'ऽ' : '\'',
    '्' : '',
    '़' : '',
    '०' : '0',
    '१' : '1',
    '२' : '2',
    '३' : '3',
    '४' : '4',
    '५' : '5',
    '६' : '6',
    '७' : '7',
    '८' : '8',
    '९' : '9',
    'ꣳ' : 'ṁ',
    '।' : '.',
    '॥' : '..',
    ' ' : ' ',
    }

input_str = input("enter a string : ")
length = len(input_str)

output_str = ""

#Converting a unicode (UTF-8) string in the sanskrit/hindi script into latinized english version
i = 0
while(i < length):
    syllable = input_str[i]
    i += 1
    while(i<length and (syllable + input_str[i] in dictionary.keys())):
        syllable += input_str[i]
        i += 1
    print("syllable = ", syllable)
    output_str += dictionary[syllable]

print(output_str)
